### ISSUE TITLE
Missing options in OpenGL for Anisotropic Filtering

### ISSUE THREAD

**Issue by niko1point0** [devkitPro/mesa#2]
I tried to do Anisotropic FIltering on Nintendo Switch with the following lines:

GLfloat maxAnisotropy = 0.0f;
glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, &maxAnisotropy);
glSamplerParameteri(sampler, GL_TEXTURE_MAX_ANISOTROPY_EXT, maxAnisotropy);

The compiler gave me an error, saying that GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT and GL_TEXTURE_MAX_ANISOTROPY_EXT were not defined. However, on Windows, I got the integer values that they hold (34046 and 34047), then I tried this code on Switch:

GLfloat maxAnisotropy = 0.0f;
glGetFloatv(34047, &maxAnisotropy);
glSamplerParameteri(sampler, 34046, maxAnisotropy);

And then Anisotropic Filtering worked perfectly fine on Nintendo Switch. I would really like it if GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT and GL_TEXTURE_MAX_ANISOTROPY_EXT can be defined in mesa, so that this feature can be easily used by anyone who wants to use the filtering feature.

Just to clearify, the reason I am posting this is because there is nothing problematic about the feature (that I know of), the feature itself appears works just fine, except the variables are not defined. All we need is 

#define GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT 34047
#define GL_TEXTURE_MAX_ANISOTROPY_EXT 34046

**Comment by fincs** [comment]
This isn't really a bug; it just means that you need to generate a [custom glad](https://glad.dav1d.de/) that loads the extensions you want on top of OpenGL 4.3 core (in this case I think you want GL_EXT_texture_filter_anisotropic). Make sure to untick the box "Generate a loader" because that doesn't work on Switch; and then you can use `gladLoadGLLoader((GLADloadproc)eglGetProcAddress)` instead of `gladLoadGL` to load the GL entrypoints.
